# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Studio Arnaud Darré
description: >-
  Product & brand designer based in London. Discover my work and profile.

# Personnal settings
github_username:  ArnaudDarre

# social links
github: https://github.com/ArnaudDarre
linkedin: https://www.linkedin.com/in/arnaud-darre/
spotify: https://open.spotify.com/user/117157101?si=rvwOIUyNR72RwV6RagJOFg

# Additional settings
timezone: Europe/London
permalink: /:title

# permalinks config
collections:
  projects:
    output: true
    permalink: /work/:path
  posts:
    output: true
    permalink: /:title

# PLUGINS
plugins:
  - jekyll-autoprefixer
  - jekyll-coffeescript
  - jekyll-inline-svg
  - jekyll-sitemap
# jekyll-inline-svg
svg:
  optimize: true
# compress vendor
# http://jch.penibelst.de/
compress_html:
  clippings: []
  comments: ["<!-- ", " -->"]
  endings: []
  ignore:
    envs: []
  blanklines: true
  profile: false
  startings: []
# autoprefixer
autoprefixer:
  browsers:
  - last 10 versions
# sass
sass:
  sass_dir: assets/_sass
  style: compressed

# Force include in processing
include:
  - _redirects

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - _backup/
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/templates/
  - .sass-cache
