# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Arnaud Darre
description: >- # this means to ignore newlines until "baseurl:"
  Print and web designer based in London. Discover my work and profile on my homemade online portfolio.

# Personnal settings
name: "Arnaud Darre"
email: arnaudarre@gmail.com
github_username:  ArnaudDarre

# social links
github: https://github.com/appliedblockchain/
linkedin: https://www.linkedin.com/company/applied-blockchain/
medium: https://medium.com/@AppBlockchain_
twitter: https://twitter.com/appblockchain

# Additional settings
timezone: Europe/London

# permalinks config
collections:
  projects:
    output: true
    permalink: /projects/:path/
  posts:
    output: true
    permalink: /:title/

# internal path
resourceurl: /public/
imageurl: /public/images/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/